export const DISTANCE_WARNING_THRESHOLD_METERS = 12;
export const DISTANCE_ERROR_THRESHOLD_METERS = 15;

export const TELEPORTATION_WARNING_THRESHOLD_KMH = 117;
export const TELEPORTATION_ERROR_THRESHOLD_KMH = 200;
