"""Idle outliers updates

Revision ID: 082a4980fd58
Revises: 746b2b7764cd
Create Date: 2026-02-26 19:34:22.704368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "082a4980fd58"
down_revision: Union[str, Sequence[str], None] = "746b2b7764cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_idle_clusters_geometry"),
        table_name="idle_clusters",
        postgresql_using="gist",
    )
    op.drop_index(
        op.f("ix_idle_clusters_geotab_database_id"), table_name="idle_clusters"
    )
    op.drop_index(op.f("ix_idle_clusters_id"), table_name="idle_clusters")
    op.drop_table("idle_clusters")
    op.drop_index(
        op.f("ix_geotab_location_db_datetime"),
        table_name="geotab_location",
        postgresql_include=["device_id", "geometry", "speed", "id"],
    )
    op.add_column(
        "idle_outlier_results", sa.Column("is_outlier", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_idle_outlier_results_is_outlier"),
        "idle_outlier_results",
        ["is_outlier"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_segment_anomaly_geotab_database_id"), table_name="road_counter_results"
    )
    op.drop_index(op.f("ix_segment_anomaly_id"), table_name="road_counter_results")
    op.drop_index(
        op.f("ix_segment_anomaly_segment_id"), table_name="road_counter_results"
    )
    op.drop_index(
        op.f("ix_segment_anomaly_validation_id"), table_name="road_counter_results"
    )
    op.create_index(
        op.f("ix_road_counter_results_geotab_database_id"),
        "road_counter_results",
        ["geotab_database_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_road_counter_results_id"), "road_counter_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_road_counter_results_segment_id"),
        "road_counter_results",
        ["segment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_road_counter_results_validation_id"),
        "road_counter_results",
        ["validation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_road_counter_results_validation_id"), table_name="road_counter_results"
    )
    op.drop_index(
        op.f("ix_road_counter_results_segment_id"), table_name="road_counter_results"
    )
    op.drop_index(op.f("ix_road_counter_results_id"), table_name="road_counter_results")
    op.drop_index(
        op.f("ix_road_counter_results_geotab_database_id"),
        table_name="road_counter_results",
    )
    op.create_index(
        op.f("ix_segment_anomaly_validation_id"),
        "road_counter_results",
        ["validation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_segment_anomaly_segment_id"),
        "road_counter_results",
        ["segment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_segment_anomaly_id"), "road_counter_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_segment_anomaly_geotab_database_id"),
        "road_counter_results",
        ["geotab_database_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_idle_outlier_results_is_outlier"), table_name="idle_outlier_results"
    )
    op.drop_column("idle_outlier_results", "is_outlier")
    op.create_index(
        op.f("ix_geotab_location_db_datetime"),
        "geotab_location",
        ["geotab_database_id", "datetime"],
        unique=False,
        postgresql_include=["device_id", "geometry", "speed", "id"],
    )
    op.create_table(
        "idle_clusters",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "geotab_database_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("cluster_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("point_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["geotab_database_id"],
            ["geotab_database.id"],
            name=op.f("idle_clusters_geotab_database_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("idle_clusters_pkey")),
    )
    op.create_index(op.f("ix_idle_clusters_id"), "idle_clusters", ["id"], unique=False)
    op.create_index(
        op.f("ix_idle_clusters_geotab_database_id"),
        "idle_clusters",
        ["geotab_database_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_idle_clusters_geometry"),
        "idle_clusters",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###
