"""geotab_feed table

Revision ID: 77ed9c51cf66
Revises: ffad6144abaa
Create Date: 2026-02-22 19:23:20.034932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77ed9c51cf66"
down_revision: Union[str, Sequence[str], None] = "ffad6144abaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geotab_feed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("geotab_database_id", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(), nullable=False),
        sa.Column("feed_version", sa.String(), nullable=True),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["geotab_database_id"],
            ["geotab_database.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_geotab_feed_geotab_database_id"),
        "geotab_feed",
        ["geotab_database_id"],
        unique=False,
    )
    op.create_index(op.f("ix_geotab_feed_id"), "geotab_feed", ["id"], unique=False)
    op.create_index(
        op.f("ix_geotab_feed_object_type"), "geotab_feed", ["object_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geotab_feed_object_type"), table_name="geotab_feed")
    op.drop_index(op.f("ix_geotab_feed_id"), table_name="geotab_feed")
    op.drop_index(op.f("ix_geotab_feed_geotab_database_id"), table_name="geotab_feed")
    op.drop_table("geotab_feed")
    # ### end Alembic commands ###
