"""geotab_location table

Revision ID: ffad6144abaa
Revises: 1cc6f73b9a0f
Create Date: 2026-02-22 18:59:25.916546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "ffad6144abaa"
down_revision: Union[str, Sequence[str], None] = "1cc6f73b9a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geotab_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("geotab_database_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geotab_database_id"],
            ["geotab_database.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_geotab_location_datetime"),
        "geotab_location",
        ["datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_location_device_id"),
        "geotab_location",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_location_external_id"),
        "geotab_location",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_location_geotab_database_id"),
        "geotab_location",
        ["geotab_database_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_location_id"), "geotab_location", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geotab_location_id"), table_name="geotab_location")
    op.drop_index(
        op.f("ix_geotab_location_geotab_database_id"), table_name="geotab_location"
    )
    op.drop_index(op.f("ix_geotab_location_external_id"), table_name="geotab_location")
    op.drop_index(op.f("ix_geotab_location_device_id"), table_name="geotab_location")
    op.drop_index(op.f("ix_geotab_location_datetime"), table_name="geotab_location")
    op.drop_index(
        "idx_geotab_location_geometry",
        table_name="geotab_location",
        postgresql_using="gist",
    )
    op.drop_table("geotab_location")
    # ### end Alembic commands ###
