"""geotab_status_data table

Revision ID: 72604a5fb799
Revises: 77ed9c51cf66
Create Date: 2026-02-22 20:28:01.073458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72604a5fb799"
down_revision: Union[str, Sequence[str], None] = "77ed9c51cf66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geotab_status_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("data", sa.Float(), nullable=True),
        sa.Column("diagnostic_name", sa.String(), nullable=True),
        sa.Column("diagnostic_unit_of_measure", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("geotab_database_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geotab_database_id"],
            ["geotab_database.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_geotab_status_data_datetime"),
        "geotab_status_data",
        ["datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_status_data_device_id"),
        "geotab_status_data",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_status_data_diagnostic_name"),
        "geotab_status_data",
        ["diagnostic_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_status_data_external_id"),
        "geotab_status_data",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_status_data_geotab_database_id"),
        "geotab_status_data",
        ["geotab_database_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geotab_status_data_id"), "geotab_status_data", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geotab_status_data_id"), table_name="geotab_status_data")
    op.drop_index(
        op.f("ix_geotab_status_data_geotab_database_id"),
        table_name="geotab_status_data",
    )
    op.drop_index(
        op.f("ix_geotab_status_data_external_id"), table_name="geotab_status_data"
    )
    op.drop_index(
        op.f("ix_geotab_status_data_diagnostic_name"), table_name="geotab_status_data"
    )
    op.drop_index(
        op.f("ix_geotab_status_data_device_id"), table_name="geotab_status_data"
    )
    op.drop_index(
        op.f("ix_geotab_status_data_datetime"), table_name="geotab_status_data"
    )
    op.drop_table("geotab_status_data")
    # ### end Alembic commands ###
