"""overture_segments table

Revision ID: 915d46c4b375
Revises: 72604a5fb799
Create Date: 2026-02-23 15:41:42.301463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '915d46c4b375'
down_revision: Union[str, Sequence[str], None] = '72604a5fb799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overture_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('geotab_database_id', sa.Integer(), nullable=False),
    sa.Column('names', sa.JSON(), nullable=True),
    sa.Column('class_code', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('road_surface', sa.JSON(), nullable=True),
    sa.Column('speed_limits', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['geotab_database_id'], ['geotab_database.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overture_segments_external_id'), 'overture_segments', ['external_id'], unique=True)
    op.create_index(op.f('ix_overture_segments_geotab_database_id'), 'overture_segments', ['geotab_database_id'], unique=False)
    op.create_index(op.f('ix_overture_segments_id'), 'overture_segments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overture_segments_id'), table_name='overture_segments')
    op.drop_index(op.f('ix_overture_segments_geotab_database_id'), table_name='overture_segments')
    op.drop_index(op.f('ix_overture_segments_external_id'), table_name='overture_segments')
    op.drop_index('idx_overture_segments_geometry', table_name='overture_segments', postgresql_using='gist')
    op.drop_table('overture_segments')
    # ### end Alembic commands ###
