"""geotab_database table

Revision ID: 1cc6f73b9a0f
Revises:
Create Date: 2026-02-21 23:12:41.954238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cc6f73b9a0f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geotab_database",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("database_name", sa.String(), nullable=False),
        sa.Column("credentials", sa.String(), nullable=False),
        sa.Column(
            "ingestion_status",
            sa.Enum(
                "NONE", "IN_PROGRESS", "DONE", name="ingestionstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_geotab_database_email"), "geotab_database", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_geotab_database_id"), "geotab_database", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geotab_database_id"), table_name="geotab_database")
    op.drop_index(op.f("ix_geotab_database_email"), table_name="geotab_database")
    op.drop_table("geotab_database")
    # ### end Alembic commands ###
