"""segment_anomaly table

Revision ID: 69959752224f
Revises: 56f4c35e3786
Create Date: 2026-02-26 06:43:34.390240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69959752224f'
down_revision: Union[str, Sequence[str], None] = '56f4c35e3786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_anomaly',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('validation_id', sa.Integer(), nullable=False),
        sa.Column('geotab_database_id', sa.Integer(), nullable=False),
        sa.Column('segment_id', sa.Integer(), nullable=False),
        sa.Column('diagnostic_id', sa.String(), nullable=False),
        sa.Column('target_avg', sa.Float(), nullable=False),
        sa.Column('historical_avg', sa.Float(), nullable=False),
        sa.Column('relative_deviation', sa.Float(), nullable=False),
        sa.Column('is_warning', sa.Boolean(), nullable=False),
        sa.Column('is_error', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['geotab_database_id'], ['geotab_database.id'], ),
        sa.ForeignKeyConstraint(['segment_id'], ['overture_segments.id'], ),
        sa.ForeignKeyConstraint(['validation_id'], ['validation.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_anomaly_diagnostic_id'), 'segment_anomaly', ['diagnostic_id'], unique=False)
    op.create_index(op.f('ix_segment_anomaly_geotab_database_id'), 'segment_anomaly', ['geotab_database_id'], unique=False)
    op.create_index(op.f('ix_segment_anomaly_id'), 'segment_anomaly', ['id'], unique=False)
    op.create_index(op.f('ix_segment_anomaly_segment_id'), 'segment_anomaly', ['segment_id'], unique=False)
    op.create_index(op.f('ix_segment_anomaly_validation_id'), 'segment_anomaly', ['validation_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_segment_anomaly_validation_id'), table_name='segment_anomaly')
    op.drop_index(op.f('ix_segment_anomaly_segment_id'), table_name='segment_anomaly')
    op.drop_index(op.f('ix_segment_anomaly_id'), table_name='segment_anomaly')
    op.drop_index(op.f('ix_segment_anomaly_geotab_database_id'), table_name='segment_anomaly')
    op.drop_index(op.f('ix_segment_anomaly_diagnostic_id'), table_name='segment_anomaly')
    op.drop_table('segment_anomaly')
