"""case_intensitive

Revision ID: 59a4fdf2533c
Revises: 915d46c4b375
Create Date: 2026-02-24 08:09:36.574502

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "59a4fdf2533c"
down_revision: Union[str, Sequence[str], None] = "915d46c4b375"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create the ICU collation
    op.execute(
        """
        CREATE COLLATION IF NOT EXISTS case_insensitive (
            provider = icu,
            locale = 'und-u-ks-level2',
            deterministic = false
        );
    """
    )

    # 2. Drop existing index on email to allow type change
    # Note: Replace 'ix_geotab_database_email' with your actual index name
    op.drop_index("ix_geotab_database_email", table_name="geotab_database")

    # 3. Alter columns to use the new collation
    op.execute(
        """
        ALTER TABLE geotab_database 
        ALTER COLUMN email TYPE VARCHAR COLLATE case_insensitive,
        ALTER COLUMN database_name TYPE VARCHAR COLLATE case_insensitive;
    """
    )

    # 4. Recreate the index (it will now be case-insensitive)
    op.create_index(
        "ix_geotab_database_email", "geotab_database", ["email"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_geotab_database_email", table_name="geotab_database")

    op.execute(
        """
        ALTER TABLE geotab_database 
        ALTER COLUMN email TYPE VARCHAR COLLATE "default",
        ALTER COLUMN database_name TYPE VARCHAR COLLATE "default";
    """
    )

    op.create_index(
        "ix_geotab_database_email", "geotab_database", ["email"], unique=False
    )
    op.execute("DROP COLLATION IF EXISTS case_insensitive")
    # ### end Alembic commands ###
