"""Distance to roads validation

Revision ID: a7c7545ea98d
Revises: b8497b84f532
Create Date: 2026-02-24 14:56:23.243674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c7545ea98d'
down_revision: Union[str, Sequence[str], None] = 'b8497b84f532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geotab_database_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_type', sa.String(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'DONE', name='validationstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['geotab_database_id'], ['geotab_database.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_geotab_database_id'), 'validation', ['geotab_database_id'], unique=False)
    op.create_index(op.f('ix_validation_id'), 'validation', ['id'], unique=False)
    op.create_index(op.f('ix_validation_started_at'), 'validation', ['started_at'], unique=False)
    op.create_index(op.f('ix_validation_status'), 'validation', ['status'], unique=False)
    op.create_table('distance_to_road_results',
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('geotab_location_id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geotab_location_id'], ['geotab_location.id'], ),
    sa.ForeignKeyConstraint(['validation_id'], ['validation.id'], ),
    sa.PrimaryKeyConstraint('geotab_location_id', 'validation_id')
    )
    op.create_index(op.f('ix_distance_to_road_results_geotab_location_id'), 'distance_to_road_results', ['geotab_location_id'], unique=False)
    op.create_index(op.f('ix_distance_to_road_results_validation_id'), 'distance_to_road_results', ['validation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distance_to_road_results_validation_id'), table_name='distance_to_road_results')
    op.drop_index(op.f('ix_distance_to_road_results_geotab_location_id'), table_name='distance_to_road_results')
    op.drop_table('distance_to_road_results')
    op.drop_index(op.f('ix_validation_status'), table_name='validation')
    op.drop_index(op.f('ix_validation_started_at'), table_name='validation')
    op.drop_index(op.f('ix_validation_id'), table_name='validation')
    op.drop_index(op.f('ix_validation_geotab_database_id'), table_name='validation')
    op.drop_table('validation')
    # ### end Alembic commands ###
