"""Distance to roads cascade delete

Revision ID: c157ece2f357
Revises: a7c7545ea98d
Create Date: 2026-02-24 15:24:50.297235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c157ece2f357'
down_revision: Union[str, Sequence[str], None] = 'a7c7545ea98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('distance_to_road_results_validation_id_fkey'),
        'distance_to_road_results',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('distance_to_road_results_validation_id_fkey'),
        'distance_to_road_results',
        'validation',
        ['validation_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('distance_to_road_results_validation_id_fkey'),
        'distance_to_road_results',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('distance_to_road_results_validation_id_fkey'),
        'distance_to_road_results',
        'validation',
        ['validation_id'],
        ['id'],
    )
    # ### end Alembic commands ###
